# airflow_settings.example.yaml
# Ce fichier est un modèle pour les configurations Airflow.
# Copiez-le en airflow_settings.yaml et remplacez les valeurs factices par les vraies valeurs.
airflow:
  connections:
    - conn_id: postgres_conn_id
      conn_type: postgres
      conn_host: postgres
      conn_schema: DWH_01
      conn_login: postgres
      conn_password: postgres
      conn_port: 5432
      conn_extra:
        example_extra_field: example-value
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: