name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment files
      run: |
        cp .env.example .env
        cp airflow_settings.example.yaml airflow_settings.yaml

    - name: Install Astro CLI
      run: |
        curl -sSL install.astronomer.io | sudo bash -s -- v1.0.0

    - name: Start Astro services
      run: |
        astro dev start

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Black on specific files
      run: |
        black --check scripts/ETL/extract.py scripts/ETL/load.py tests/dags/test_data_quality.py tests/dags/test_extract.py

    - name: Run tests in specific directories
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/DWH_01
      run: |
        pytest tests/dags/test_data_quality.py tests/dags/test_extract.py

    - name: Stop Astro services
      run: |
        astro dev stop