name: check_code_quality
on: pull_request
jobs: 
  black:
  runs-on: ubuntu-20.24
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setups-python@v4
      with:
        python-version: 3.9
    - run: |
        python -m pip install --upgrade pip 
        pip install black
    - run: |
        black --check --verbose .