name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t astro-project-dwh .

    - name: Run Docker container
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/DWH_01
      run: |
        docker run -d --name astro-project-dwh \
          -e DATABASE_URL=$DATABASE_URL \
          astro-project-dwh
          
        # Attendre que le service démarre
        sleep 10  

    - name: Run tests inside container
      run: |
        docker exec astro-project-dwh bash -c "
          black --check scripts/ETL/extract.py \
                         scripts/ETL/load.py \
                         tests/dags/test_data_quality.py \
                         tests/dags/test_extract.py && 
          pytest tests/dags/test_data_quality.py \
                 tests/dags/test_extract.py
        "

    - name: Stop and remove Docker container
      if: always()
      run: |
        docker stop astro-project-dwh
        docker rm astro-project-dwh
