name: Data Quality Tests

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche main
  pull_request:
    branches:
      - main  # Déclenche le workflow lors d'une pull request sur la branche main

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout le code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances Python

    - name: Install Astro CLI
      run: |
        curl -sSL install.astronomer.io | sudo bash -s  # Installe l'Astro CLI

    - name: Start Astro services
      run: |
        astro dev start  # Démarre les services Airflow et PostgreSQL

    - name: Run data quality tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres  # Utilisateur PostgreSQL par défaut d'Astro
        POSTGRES_PASSWORD: postgres  # Mot de passe PostgreSQL par défaut d'Astro
        POSTGRES_DB: DWH_01  # Nom de la base de données que vous avez créée
      run: |
        pytest tests/dags/test_data_quality.py tests/dags/test_extract.py  # Exécute les tests avec pytest

    - name: Stop Astro services
      run: |
        astro dev stop  # Arrête les services après les tests